name: validate

on:
  push:

jobs:
  code_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: maven-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: validate
        run: mvn clean test
      - name: build
        run: mvn clean install -DskipTests
      - name: deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: mvn --settings contrast-artifactory-setting.xml deploy